Agrahim.API/Areas/Admin/Controllers/CropsController.cs
using System.Threading;
using System.Threading.Tasks;
using Agrahim.Common.DTOs;
using Agrahim.Common.ViewModels.Crops;
using Agrahim.Domain.ServicesContracts;
using Agrahim.Infrastructure.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Agrahim.API.Areas.Admin.Controllers
{
    [Area("admin")]
    [Route("[area]/crops")]
    [Authorize(Roles = UserEntity.RoleAdmin)]
    public class CropsController : Controller
    {
        private readonly ICropsService _cropsService;

        public CropsController(ICropsService cropsService)
        {
            _cropsService = cropsService;
        }

        [HttpGet]
        [Route("")]
        [Route("index")]
        public async Task<IActionResult> Index(CancellationToken ct = default)
        {
            var crops = await _cropsService.GetAll(ct);
            return View(crops);
        }

        [HttpGet]
        [Route("create")]
        public async Task<IActionResult> Create(CancellationToken ct = default)
        {
            await PopulateCropsTypesDropDownList(ct);
            return View();
        }
        
        [HttpPost]
        [Route("create")]
        public async Task<IActionResult> Create(CreateCropViewModel model, CancellationToken ct = default)
        {
            if (!ModelState.IsValid)
            {
                await PopulateCropsTypesDropDownList(ct);
                return View();
            }

            if (!await _cropsService.IsUniq(model.Name, ct))
            {
                ModelState.AddModelError("", "Название культуры должны быть уникальным.");
                return View();
            }

            await _cropsService.Create(model, ct);            
            
            return RedirectToAction(nameof(Index));
        }

        private async Task PopulateCropsTypesDropDownList(CancellationToken ct = default)
        {
            var cropsTypes = await _cropsService.GetCropsTypeToSelect(ct);
            ViewBag.CropsTypes = new SelectList(
                cropsTypes, 
                nameof(CropsTypeToSelectDto.Id),
                nameof(CropsTypeToSelectDto.Name));
        }
    }
}

Agrahim.API/Areas/Admin/Views/Crops/Create.cshtml
@using Agrahim.Common.DTOs
@model Agrahim.Common.ViewModels.Crops.CreateCropViewModel

@{
    ViewBag.Title = "Cоздание культуры";
    Layout = "_Layout";
}

<div class="row justify-content-center">
    <div class="col-8">
        <h2>@ViewBag.Title</h2>
        <form method="post" asp-area="Admin" asp-controller="Crops" asp-action="Create">
            <div asp-validation-summary="ModelOnly"></div>
            <div class="form-group">
                <label asp-for="Name" for="nameInput"></label><br/>
                <input asp-for="Name" id="nameInput" class="form-control"/>
                <span asp-validation-for="Name"></span>
            </div>
            <div class="form-group">
                <label asp-for="CropsTypeId" class="control-label"></label>
                <select asp-for="CropsTypeId" class="form-control" asp-items="ViewBag.CropsTypes">
                    <option value="">Выберите тип культуры</option>
                </select>
                <span asp-validation-for="CropsTypeId"></span>
            </div>
            <input class="btn btn-success" type="submit" value="Создать"/>
        </form>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

@section Css
{
    @{
        await Html.RenderPartialAsync("_ValidationCssPartial");
    }
}

Agrahim.API/Areas/Admin/Views/Crops/Index.cshtml
@model IEnumerable<Agrahim.Common.DTOs.CropDto>

@{
    ViewBag.Title = "Культуры";
    Layout = "_Layout";
}

<h2>@ViewBag.Title</h2>

<div>
    <a class="btn btn-outline-success" asp-area="Admin" asp-controller="Crops" asp-action="Create">Создать</a>
</div>

<div class="mt-1">
    <table class="table table-bordered">
        <thead>
        <tr>
            <th>Id</th>
            <th>Название</th>
            <th>Тип культуры</th>
            <th>Статус</th>
            <th>Действия</th>
        </tr>
        </thead>
        <tbody>
        @foreach (var crops in Model)
        {
            <tr>
                <td>@crops.Id</td>
                <td>@crops.Name</td>
                <td>@crops.CropsTypeName</td>
                <td>@(crops.IsRemoved ? "Неактивен" : "Действует")</td>
                <td>
                    <a 
                        class="btn btn-outline-info" 
                        asp-area="Admin" 
                        asp-controller="Crops" 
                        asp-action="Index"
                        asp-route-id=@crops.Id>
                        <i class="fa fa-edit"></i>
                    </a>
                </td>
            </tr>
        }
        </tbody>
    </table>
</div>