Agrahim.API/Areas/Admin/Controllers/CropsTypesController.cs
using System;
using System.Threading;
using System.Threading.Tasks;
using Agrahim.Common.ViewModels;
using Agrahim.Common.ViewModels.CropsType;
using Agrahim.Domain.ServicesContracts;
using Agrahim.Infrastructure.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Agrahim.API.Areas.Admin.Controllers
{
    [Area("admin")]
    [Route("[area]/crops-types")]
    [Authorize(Roles = UserEntity.RoleAdmin)]
    public class CropsTypesController : Controller
    {
        private readonly ICropsTypesService _cropsTypesService;

        public CropsTypesController(ICropsTypesService cropsTypesService)
        {
            _cropsTypesService = cropsTypesService;
        }

        [Route("")]
        [Route("index")]
        [HttpGet]
        public async Task<IActionResult> Index(CancellationToken ct = default)
        {
            var cropsTypes = await _cropsTypesService.GetAll(ct);
            return View(cropsTypes);
        }

        [HttpGet]
        [Route("create")]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [Route("create")]
        public async Task<IActionResult> Create(CreateCropsTypeViewModel model, CancellationToken ct = default)
        {
            // Валидация модели
            if (!ModelState.IsValid) return View();

            if (!await _cropsTypesService.IsUniq(model.Name, ct))
            {
                ModelState.AddModelError("", "Название типа культуры должны быть уникальным.");
                return View();
            }
            
            await _cropsTypesService.Create(model, ct);
            return RedirectToAction("Index");
        }

        [HttpGet("disable/{id}")]
        public async Task<IActionResult> Disable(long id, CancellationToken ct)
        {
            await _cropsTypesService.Disable(id, ct);
            return RedirectToAction("Index");
        }

        [HttpGet("update/{id}")]
        public async Task<IActionResult> Update(long id, CancellationToken ct)
        {
            var cropsType = await _cropsTypesService.GetById(id, ct);
            return View(cropsType);
        }
        
        [HttpPost("update/{id}")]
        public async Task<IActionResult> Update(UpdateCropsTypeViewModel model, CancellationToken ct)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }

            await _cropsTypesService.Update(model, ct);
            return RedirectToAction("Index");
        }
    }
}

Agrahim.API/Areas/Admin/Views/CropsTypes/Create.cshtml
@model Agrahim.Common.ViewModels.CropsType.CreateCropsTypeViewModel

@{
    ViewBag.Title = "Создание типа культуры";
    Layout = "_Layout";
}

<div class="row justify-content-center">
    <div class="col-8">
        <h2>@ViewBag.Title</h2>
        <form method="post" asp-area="Admin" asp-controller="CropsTypes" asp-action="Create">
            <div asp-validation-summary="ModelOnly"></div>
            <div class="form-group">
                <label asp-for="Name" for="nameInput"></label><br/>
                <input asp-for="Name" id="nameInput" class="form-control"/>
                <span asp-validation-for="Name"></span>
            </div>
            <div class="form-group">
                <label asp-for="CoefficientN" for="nInput"></label><br/>
                <input asp-for="CoefficientN" id="nInput" class="form-control"/>
                <span asp-validation-for="CoefficientN"></span>
            </div>
            <div class="form-group">
                <label asp-for="CoefficientP" for="CoefficientP"></label><br/>
                <input asp-for="CoefficientP" id="CoefficientP" class="form-control"/>
                <span asp-validation-for="CoefficientP"></span>
            </div>
            <div class="form-group">
                <label asp-for="CoefficientK" for="CoefficientK"></label><br/>
                <input asp-for="CoefficientK" id="CoefficientK" class="form-control"/>
                <span asp-validation-for="CoefficientK"></span>
            </div>
            <input class="btn btn-success" type="submit" value="Создать"/>
        </form>
    </div>
</div>


@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

@section Css
{
    @{
        await Html.RenderPartialAsync("_ValidationCssPartial");
    }
}

Agrahim.API/Areas/Admin/Views/CropsTypes/Index.cshtml
@model IEnumerable<Agrahim.Common.DTOs.CropsTypeDto>
@{
    ViewBag.Title = "Типы культур";
    Layout = "_Layout";
}

<h2>@ViewBag.Title</h2>

<div>
    <a class="btn btn-outline-success" asp-area="Admin" asp-controller="CropsTypes" asp-action="Create">Создать</a>
</div>

<div class="mt-1">
    <table class="table table-bordered">
        <thead>
        <tr>
            <th>Id</th>
            <th>Название</th>
            <th>N</th>
            <th>P</th>
            <th>K</th>
            <th>Статус</th>
            <th>Действия</th>
        </tr>
        </thead>
        <tbody>
        @foreach (var cropsType in Model)
        {
            <tr>
                <td>@cropsType.Id</td>
                <td>@cropsType.Name</td>
                <td>@cropsType.CoefficientN</td>
                <td>@cropsType.CoefficientP</td>
                <td>@cropsType.CoefficientK</td>
                <td>@(cropsType.IsRemoved ? "Неактивен" : "Действует")</td>
                <td>
                    <a 
                        class="btn btn-outline-info" 
                        asp-area="Admin" 
                        asp-controller="CropsTypes" 
                        asp-action="Update"
                        asp-route-id=@cropsType.Id>
                        <i class="fa fa-edit"></i>
                    </a>
                </td>
            </tr>
        }
        </tbody>
    </table>
</div>

Agrahim.API/Areas/Admin/Views/CropsTypes/Update.cshtml
@model Agrahim.Common.ViewModels.CropsType.UpdateCropsTypeViewModel
@{
    ViewBag.Title = "Редактирование";
    Layout = "_Layout";
}

<div class="row justify-content-center">
    <div class="col-8">
        <h2>@ViewBag.Title</h2>
        <form method="post" asp-area="Admin" asp-controller="CropsTypes" asp-action="Update">
            <div asp-validation-summary="ModelOnly"></div>
            <div class="form-group">
                <label asp-for="Name" for="nameInput"></label><br/>
                <input asp-for="Name" id="nameInput" class="form-control"/>
                <span asp-validation-for="Name"></span>
            </div>
            <div class="form-group">
                <label asp-for="CoefficientN" for="CoefficientN"></label><br/>
                <input asp-for="CoefficientN" id="CoefficientN" class="form-control"/>
                <span asp-validation-for="CoefficientN"></span>
            </div>
            <div class="form-group">
                <label asp-for="CoefficientP" for="CoefficientP"></label><br/>
                <input asp-for="CoefficientP" id="CoefficientP" class="form-control"/>
                <span asp-validation-for="CoefficientP"></span>
            </div>
            <div class="form-group">
                <label asp-for="CoefficientK" for="CoefficientK"></label><br/>
                <input asp-for="CoefficientK" id="CoefficientK" class="form-control"/>
                <span asp-validation-for="CoefficientK"></span>
            </div>
            <div class="form-check">
                <input asp-for="IsRemoved" type="checkbox" class="form-check-input" id="isRemoved">
                <label asp-for="IsRemoved" class="form-check-label" for="isRemoved">Удален</label>
                <span asp-validation-for="IsRemoved"></span>
            </div>
            <input class="btn btn-success" type="submit" value="Обновить"/>
        </form>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

@section Css
{
    @{
        await Html.RenderPartialAsync("_ValidationCssPartial");
    }
}